#comment out embeddings which are not used

#RESAMPLING_EMBEDDING = True
DISSIMILARITY_EMBEDDING = True

ORIGINAL_DISTANCE = "mam"
EMBEDDED_DISTANCE = "euclidean"
#EMBEDDED_DISTANCE = "mam"
#EMBEDDED_DISTANCE = "mdf"

STRESS = True
#PEARSON_CORRELATION = True
#DISTORSION = True

